name: Build, Test, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build and Push Docker Image
        uses: carrotincentives/build-maven-action@v1
        with:
          # Repository Checkout
          checkout_ref: 'main'

          # Java and Maven Configuration
          java_version: '11'
          java_distribution: 'zulu'
          maven_version: '3.8.4'
          maven_options: '-U clean package -DskipTests'

          # Docker Build & Tagging
          dockerfile_path: './Dockerfile'
          image_name: 'my-java-app'
          build_version: 'v1.0.0'

          # Docker Registry Credentials
          registry_url: 'docker.io'
          registry_username: 'your-username'
          registry_password: 'your-password'